# Generated by Django 5.0.6 on 2024-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseFoot2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=30)),
                ('data_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataBaseFoot3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=30)),
                ('data_value', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DataBaseFoot',
            new_name='DataBaseFoot1',
        ),
    ]
