# Generated by Django 5.0.6 on 2024-05-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0002_databasefoot2_databasefoot3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataBaseFoot1',
            new_name='DataBaseFoot',
        ),
    ]
