# Generated by Django 5.0.6 on 2024-05-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0003_rename_databasefoot1_databasefoot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataBaseFoot',
            new_name='DataBaseFoot1',
        ),
    ]
