# Generated by Django 5.0.6 on 2024-05-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0004_rename_databasefoot_databasefoot1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseFoot1Presion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.CharField(max_length=30)),
                ('data_value', models.IntegerField()),
            ],
        ),
    ]
